# Generated by Django 3.2.9 on 2022-02-14 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Watchlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='update_url',
        ),
    ]
