# Generated by Django 3.2.9 on 2022-02-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Watchlist', '0002_remove_watchlist_update_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='watched',
            field=models.BooleanField(default=False),
        ),
    ]
