# Generated by Django 3.2.9 on 2022-02-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Watchlist', '0003_alter_watchlist_watched'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='added_by_bot',
            field=models.BooleanField(default=False),
        ),
    ]
