# Generated by Django 3.2.9 on 2022-02-16 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Watchlist', '0004_watchlist_added_by_bot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='added_by_bot',
            new_name='available',
        ),
    ]
