# Generated by Django 3.2.9 on 2022-02-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Watchlist', '0005_rename_added_by_bot_watchlist_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='last_watched',
            field=models.BooleanField(default=False),
        ),
    ]
